import os
import sys
import traceback
import argparse
from pathlib import Path
from typing import Optional

# Allow importing local project modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from datasets import PcapDatasetLoader, CNNPRECSVDatasetLoader
from temp_evaluator import RPKClustEvaluator


# ---------------------------------------------------------------------------
# NetPlier benchmark datasets (PCAP)
# ---------------------------------------------------------------------------
#
# The directory contains:
#
#   dhcp_100.pcap
#   dnp3_100.pcap
#   icmp_100.pcap
#   modbus_100.pcap
#   ntp_100.pcap
#   smb_100.pcap
#   smb2_100.pcap
#   tftp_100.pcap
#
# The protocol name is NOT inferred from the first byte of a message.
# It is explicitly associated with the PCAP filename.
#
# Ground-truth labels are generated by PcapDatasetLoader using the same
# protocol-specific fields used by NetPlier.
# ---------------------------------------------------------------------------

NETPLIER_DATASETS = {
    "dhcp_100.pcap": "dhcp",
    "dnp3_100.pcap": "dnp3",
    "icmp_100.pcap": "icmp",
    "modbus_100.pcap": "modbus",
    "ntp_100.pcap": "ntp",
    "smb_100.pcap": "smb",
    "smb2_100.pcap": "smb2",
    "tftp_100.pcap": "tftp",
}


# ---------------------------------------------------------------------------
# CNNPRE benchmark datasets (CSV)
# ---------------------------------------------------------------------------
#
# Pre-processed CSV datasets from CNNPRE project.
# Each CSV contains: direction, type, hex, Full
# - type is the ground-truth message type
# - hex is the packet payload in hex format
# - direction: 0=request, 1=response
#
# These are mapped by filename to protocol names.
# Available files in CNNPRE/Data/:
# ---------------------------------------------------------------------------

CNNPRE_DATASETS = {
    "DHCP921-hex.csv": "dhcp",
    "ICMP3231-hex.csv": "icmp",
    "NTP1043-hex.csv": "ntp",
    "DNS4876-hex.csv": "dns",
    "HTTP1963-hex.csv": "http",
    "FTP1620-hex.csv": "ftp",
    "SMTP1172-hex.csv": "smtp",
    "POP1080-hex.csv": "pop3",
    "NBNS2642-hex.csv": "nbns",
    "ARP1275-hex.csv": "arp",
    "GSM5000-hex.csv": "gsm",
    "SYSLOG1792-hex.csv": "syslog",
}


# ---------------------------------------------------------------------------
# RPKClust isolation
# ---------------------------------------------------------------------------
#
# Guide items 14/15: ground truth must never reach RPKClust. The loader
# returns GT inside the metadata records for the evaluator, so the
# metadata is projected through this allow-list before fit().
# ---------------------------------------------------------------------------

RPKCLUST_METADATA_FIELDS = (
    "timestamp",
    "protocol",
    "transport",
    "direction",
    "source_ip",
    "source_port",
    "destination_ip",
    "destination_port",
    "session_id",
    "packet_index",
    "payload_length",
)

# Anything that encodes or derives from the ground truth is forbidden in
# the metadata handed to RPKClust.
GROUND_TRUTH_FIELDS = frozenset(
    {
        "gt_value",
        "gt_label",
        "gt_source",
        "true_keyword",
        "keyword_offset",
    }
)


def project_metadata_for_rpkclust(
    metadata,
):
    """
    Strip every ground-truth field before handing metadata to RPKClust.

    This is the single enforcement point for the isolation rule.
    """

    if not metadata:
        return None

    projected = []

    for record in metadata:

        entry = {
            field: record[field]
            for field in RPKCLUST_METADATA_FIELDS
            if field in record
        }

        assert not (set(entry) & GROUND_TRUTH_FIELDS), (
            "ground-truth field leaked into RPKClust input: "
            f"{sorted(set(entry) & GROUND_TRUTH_FIELDS)}"
        )

        assert not any(
            key.lower().startswith("gt") for key in entry
        ), f"ground-truth-like field leaked into RPKClust input: {sorted(entry)}"

        projected.append(entry)

    return projected


def print_dataset_diagnostics(
    protocol,
    X,
    y,
    metadata,
    stats,
):
    """Guide item 16: make parser/dataset errors visible before RPKClust."""

    directions = {}
    for record in metadata:
        key = record.get("direction", "unknown")
        directions[key] = directions.get(key, 0) + 1

    gt_values = {
        record.get("gt_value") for record in metadata
    }

    print()
    print("-" * 65)
    print(f"  EXTRACTION DIAGNOSTICS: {protocol}")
    print("-" * 65)
    print(f"  protocol                     : {protocol}")
    if stats:
        print(f"  packets read                 : {stats.get('packets_read', 'N/A (CSV)')}")
        print(f"  link types                   : {stats.get('link_types', 'N/A (CSV)')}")
        print(f"  transport payloads           : {stats.get('transport_payloads', 'N/A (CSV)')}")
        print(f"  skipped empty/short          : {stats.get('skipped_empty', 'N/A (CSV)')}")
        print(f"  skipped unsupported          : {stats.get('skipped_unsupported', 'N/A (CSV)')}")
        print(f"  skipped truncated            : {stats.get('skipped_truncated', 'N/A (CSV)')}")
        print(f"  skipped by preprocessing     : {stats.get('skipped_preprocess', 'N/A (CSV)')}")
        print(f"  skipped (no GT available)    : {stats.get('skipped_no_gt', 'N/A (CSV)')}")

    print(f"  extracted messages           : {len(X)}")
    print(f"  requests                     : {directions.get('request', 0)}")
    print(f"  responses                    : {directions.get('response', 0)}")
    print(f"  unknown directions           : {directions.get('unknown', 0)}")
    print(f"  unique GT values             : {len(gt_values)}")
    print(f"  GT classes (label space)     : {len(set(y)) if y is not None else 0}")

    if len(X) > 1:
        lengths = sorted(len(message) for message in X)
        print(f"  message length min/median/max: "
              f"{lengths[0]} / {lengths[len(lengths) // 2]} / {lengths[-1]}")

    sessions = {
        record.get("session_id") for record in metadata
    }

    print(f"  sessions                     : {len(sessions)}")
    print("-" * 65)


def evaluate_dataset(
    loader,
    evaluator: RPKClustEvaluator,
    dataset_file: Path,
    protocol: str,
    source_type: str,
    max_samples: Optional[int] = None,
):
    """
    Load one dataset (PCAP or CSV) and evaluate RPKClust.

    The protocol is explicitly supplied because ground truth
    extraction is protocol-specific.

    RPKClust receives the extracted messages and interaction metadata.
    The labels are used only by the evaluator.
    """

    dataset_name = dataset_file.stem

    print()
    print("=" * 65)
    print(f"Evaluating: {dataset_name}")
    print(f"Protocol:   {protocol}")
    print(f"Source:     {source_type}")
    print("=" * 65)

    # Load data based on loader type
    if isinstance(loader, PcapDatasetLoader):
        X, y, metadata = loader.extract_payloads_with_metadata(
            str(dataset_file),
            protocol=protocol,
        )
        stats = dict(loader.last_stats)
    else:  # CNNPRECSVDatasetLoader
        X, y, metadata = loader.extract_payloads_with_metadata(
            str(dataset_file),
            protocol=protocol,
            max_samples=max_samples,
        )
        stats = None

    if not X:
        print(f"[WARNING] No messages extracted from {dataset_file.name}")
        return

    print_dataset_diagnostics(
        protocol,
        X,
        y,
        metadata,
        stats,
    )

    # ------------------------------------------------------------------
    # IMPORTANT:
    #
    # RPKClust must cluster X without receiving ground-truth information.
    #
    # The evaluator is responsible for comparing the predicted clusters
    # against y.
    # ------------------------------------------------------------------

    fit_metadata = project_metadata_for_rpkclust(metadata)

    timestamps = [
        record["timestamp"]
        for record in metadata
        if record.get("timestamp") is not None
    ]

    direction_labels = [
        record.get("direction", "unknown")
        for record in metadata
    ]

    fit_kwargs = {
        "interaction_metadata": fit_metadata,
    }

    # The Timestamp semantic rule (rule 3) is disabled without a capture
    # window; RPKClust's fit() exposes capture_start/capture_end for this.
    if timestamps:
        fit_kwargs["capture_start"] = min(timestamps)
        fit_kwargs["capture_end"] = max(timestamps)

    fit_kwargs["direction_labels"] = direction_labels

    return evaluator.run_diagnostics(
        X,
        y,
        dataset_name=dataset_name,
        fit_kwargs=fit_kwargs,
    )


def parse_args():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="RPKClust Evaluation - NetPlier and CNNPRE Datasets",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run on all NetPlier PCAP datasets (default)
  python main.py

  # Run on all CNNPRE CSV datasets
  python main.py --source csv

  # Run on specific PCAP dataset
  python main.py --source pcap --protocol dhcp

  # Run on specific CNNPRE CSV dataset
  python main.py --source csv --protocol dhcp

  # Run on CNNPRE CSV with sample limit
  python main.py --source csv --protocol http --max-samples 1000
        """
    )
    parser.add_argument(
        "--source",
        choices=["pcap", "csv", "both"],
        default="pcap",
        help="Data source: 'pcap' (NetPlier), 'csv' (CNNPRE), or 'both' (default: pcap)"
    )
    parser.add_argument(
        "--protocol",
        type=str,
        help="Specific protocol to evaluate (e.g., dhcp, dns, http). If omitted, evaluates all available datasets for the chosen source."
    )
    parser.add_argument(
        "--max-samples",
        type=int,
        default=None,
        help="Maximum number of samples to load per CSV dataset (CNNPRE only)."
    )
    parser.add_argument(
        "--list-datasets",
        action="store_true",
        help="List available datasets and exit."
    )
    return parser.parse_args()


def list_datasets():
    """Print available datasets for both sources."""
    print("=" * 65)
    print("Available Datasets")
    print("=" * 65)

    print("\nNetPlier PCAP datasets (Implementation/datasets/downloads/):")
    for fname, proto in NETPLIER_DATASETS.items():
        print(f"  {proto:<10} -> {fname}")

    print("\nCNNPRE CSV datasets (CNNPRE/Data/):")
    for fname, proto in CNNPRE_DATASETS.items():
        print(f"  {proto:<10} -> {fname}")

    print()


def main():
    args = parse_args()

    if args.list_datasets:
        list_datasets()
        return

    print("=" * 65)
    print(f"RPKClust Evaluation - Data Source: {args.source.upper()}")
    print("=" * 65)

    # ------------------------------------------------------------------
    # Paths (resolved relative to this file, not the CWD)
    # ------------------------------------------------------------------

    base_dir = Path(__file__).resolve().parent
    results_dir = base_dir / "results"

    # Initialize evaluator
    evaluator = RPKClustEvaluator(
        output_dir=str(results_dir),
        fig_format="png",
        dpi=300,
    )

    # Determine which datasets to evaluate
    datasets_to_eval = []  # List of (loader, dataset_file, protocol, source_type)

    if args.source in ("pcap", "both"):
        downloads_dir = base_dir / "datasets" / "downloads"
        if downloads_dir.exists():
            pcap_loader = PcapDatasetLoader(target_dir=str(downloads_dir))
            for filename, protocol in NETPLIER_DATASETS.items():
                if args.protocol and protocol != args.protocol:
                    continue
                pcap_file = downloads_dir / filename
                if pcap_file.exists():
                    datasets_to_eval.append((
                        pcap_loader, pcap_file, protocol, "NetPlier PCAP"
                    ))
                else:
                    print(f"[WARNING] Missing PCAP dataset: {pcap_file}")

    if args.source in ("csv", "both"):
        cnnp_dir = base_dir.parent / "CNNPRE" / "Data"
        if cnnp_dir.exists():
            csv_loader = CNNPRECSVDatasetLoader(target_dir=str(cnnp_dir))
            for filename, protocol in CNNPRE_DATASETS.items():
                if args.protocol and protocol != args.protocol:
                    continue
                csv_file = cnnp_dir / filename
                if csv_file.exists():
                    datasets_to_eval.append((
                        csv_loader, csv_file, protocol, "CNNPRE CSV"
                    ))
                else:
                    print(f"[WARNING] Missing CSV dataset: {csv_file}")

    if not datasets_to_eval:
        raise FileNotFoundError(
            f"No datasets found for source '{args.source}' "
            f"and protocol '{args.protocol or 'all'}'"
        )

    print()
    print(f"Found {len(datasets_to_eval)} datasets to evaluate:")
    print()

    for loader, dataset_file, protocol, source_type in datasets_to_eval:
        print(f"  {protocol:<10} -> {dataset_file.name} ({source_type})")

    print()

    # ------------------------------------------------------------------
    # Evaluate every dataset.
    # A failure on one dataset must not abort the whole benchmark.
    # ------------------------------------------------------------------

    failures = []

    for loader, dataset_file, protocol, source_type in datasets_to_eval:

        try:

            evaluate_dataset(
                loader=loader,
                evaluator=evaluator,
                dataset_file=dataset_file,
                protocol=protocol,
                source_type=source_type,
                max_samples=args.max_samples,
            )

        except Exception as exc:

            failures.append((dataset_file.name, protocol, source_type, exc))

            print()
            print(f"[FAILED] {protocol} ({dataset_file.name}, {source_type})")
            print(f"  {type(exc).__name__}: {exc}")
            traceback.print_exc()

    # ------------------------------------------------------------------
    # Export combined evaluation results
    # ------------------------------------------------------------------

    print()
    print("=" * 65)
    print("Exporting summary artifacts")
    print("=" * 65)

    evaluator.export_summary_artifacts()

    if failures:

        print()
        print("=" * 65)
        print("INCOMPLETE BENCHMARK")
        print("=" * 65)

        for filename, protocol, source_type, exc in failures:
            print(f"  {protocol:<10} {filename:<25} {source_type:<15} {exc}")

        print()

    print()
    print("Evaluation completed successfully.")


if __name__ == "__main__":
    main()