import os
import sys
import traceback
from pathlib import Path

# Allow importing local project modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from datasets import PcapDatasetLoader
from temp_evaluator import RPKClustEvaluator


# ---------------------------------------------------------------------------
# NetPlier benchmark datasets
# ---------------------------------------------------------------------------
#
# The directory contains:
#
#   dhcp_100.pcap
#   dnp3_100.pcap
#   icmp_100.pcap
#   modbus_100.pcap
#   ntp_100.pcap
#   smb_100.pcap
#   smb2_100.pcap
#   tftp_100.pcap
#
# The protocol name is NOT inferred from the first byte of a message.
# It is explicitly associated with the PCAP filename.
#
# Ground-truth labels are generated by PcapDatasetLoader using the same
# protocol-specific fields used by NetPlier.
# ---------------------------------------------------------------------------

NETPLIER_DATASETS = {
    "dhcp_100.pcap": "dhcp",
    "dnp3_100.pcap": "dnp3",
    "icmp_100.pcap": "icmp",
    "modbus_100.pcap": "modbus",
    "ntp_100.pcap": "ntp",
    "smb_100.pcap": "smb",
    "smb2_100.pcap": "smb2",
    "tftp_100.pcap": "tftp",
}


# ---------------------------------------------------------------------------
# RPKClust isolation
# ---------------------------------------------------------------------------
#
# Guide items 14/15: ground truth must never reach RPKClust. The loader
# returns GT inside the metadata records for the evaluator, so the
# metadata is projected through this allow-list before fit().
# ---------------------------------------------------------------------------

RPKCLUST_METADATA_FIELDS = (
    "timestamp",
    "protocol",
    "transport",
    "direction",
    "source_ip",
    "source_port",
    "destination_ip",
    "destination_port",
    "session_id",
    "packet_index",
    "payload_length",
)

# Anything that encodes or derives from the ground truth is forbidden in
# the metadata handed to RPKClust.
GROUND_TRUTH_FIELDS = frozenset(
    {
        "gt_value",
        "gt_label",
        "gt_source",
        "true_keyword",
        "keyword_offset",
    }
)


def project_metadata_for_rpkclust(
    metadata,
):
    """
    Strip every ground-truth field before handing metadata to RPKClust.

    This is the single enforcement point for the isolation rule.
    """

    if not metadata:
        return None

    projected = []

    for record in metadata:

        entry = {
            field: record[field]
            for field in RPKCLUST_METADATA_FIELDS
            if field in record
        }

        assert not (set(entry) & GROUND_TRUTH_FIELDS), (
            "ground-truth field leaked into RPKClust input: "
            f"{sorted(set(entry) & GROUND_TRUTH_FIELDS)}"
        )

        assert not any(
            key.lower().startswith("gt") for key in entry
        ), f"ground-truth-like field leaked into RPKClust input: {sorted(entry)}"

        projected.append(entry)

    return projected


def print_dataset_diagnostics(
    protocol,
    X,
    y,
    metadata,
    stats,
):
    """Guide item 16: make parser/dataset errors visible before RPKClust."""

    directions = {}
    for record in metadata:
        key = record.get("direction", "unknown")
        directions[key] = directions.get(key, 0) + 1

    gt_values = {
        record.get("gt_value") for record in metadata
    }

    print()
    print("-" * 65)
    print(f"  EXTRACTION DIAGNOSTICS: {protocol}")
    print("-" * 65)
    print(f"  protocol                     : {protocol}")
    print(f"  packets read                 : {stats.get('packets_read')}")
    print(f"  link types                   : {stats.get('link_types')}")
    print(f"  transport payloads           : {stats.get('transport_payloads')}")
    print(f"  extracted messages           : {len(X)}")
    print(f"  requests                     : {directions.get('request', 0)}")
    print(f"  responses                    : {directions.get('response', 0)}")
    print(f"  unknown directions           : {directions.get('unknown', 0)}")
    print(f"  unique GT values             : {len(gt_values)}")
    print(f"  GT classes (label space)     : {len(set(y)) if y is not None else 0}")
    print(f"  skipped empty/short          : {stats.get('skipped_empty')}")
    print(f"  skipped unsupported          : {stats.get('skipped_unsupported')}")
    print(f"  skipped truncated            : {stats.get('skipped_truncated')}")
    print(f"  skipped by preprocessing     : {stats.get('skipped_preprocess')}")
    print(f"  skipped (no GT available)    : {stats.get('skipped_no_gt')}")

    if stats.get("reassembly"):
        print(f"  TCP reassembly               : {stats['reassembly']}")

    if len(X) > 1:
        lengths = sorted(len(message) for message in X)
        print(f"  message length min/median/max: "
              f"{lengths[0]} / {lengths[len(lengths) // 2]} / {lengths[-1]}")

    sessions = {
        record.get("session_id") for record in metadata
    }

    print(f"  sessions                     : {len(sessions)}")
    print("-" * 65)


def evaluate_pcap(
    loader: PcapDatasetLoader,
    evaluator: RPKClustEvaluator,
    pcap_file: Path,
    protocol: str,
):
    """
    Load one NetPlier capture and evaluate RPKClust.

    The protocol is explicitly supplied because NetPlier's ground truth
    extraction is protocol-specific.

    RPKClust receives the extracted messages and interaction metadata.
    The labels are used only by the evaluator.
    """

    dataset_name = pcap_file.stem

    print()
    print("=" * 65)
    print(f"Evaluating: {dataset_name}")
    print(f"Protocol:   {protocol}")
    print("=" * 65)

    X, y, metadata = loader.extract_payloads_with_metadata(
        str(pcap_file),
        protocol=protocol,
    )

    stats = dict(loader.last_stats)

    if not X:
        print(f"[WARNING] No messages extracted from {pcap_file.name}")
        return

    print_dataset_diagnostics(
        protocol,
        X,
        y,
        metadata,
        stats,
    )

    # ------------------------------------------------------------------
    # IMPORTANT:
    #
    # RPKClust must cluster X without receiving ground-truth information.
    #
    # The evaluator is responsible for comparing the predicted clusters
    # against y.
    # ------------------------------------------------------------------

    fit_metadata = project_metadata_for_rpkclust(metadata)

    timestamps = [
        record["timestamp"]
        for record in metadata
        if record.get("timestamp") is not None
    ]

    direction_labels = [
        record.get("direction", "unknown")
        for record in metadata
    ]

    fit_kwargs = {
        "interaction_metadata": fit_metadata,
    }

    # The Timestamp semantic rule (rule 3) is disabled without a capture
    # window; RPKClust's fit() exposes capture_start/capture_end for this.
    if timestamps:
        fit_kwargs["capture_start"] = min(timestamps)
        fit_kwargs["capture_end"] = max(timestamps)

    fit_kwargs["direction_labels"] = direction_labels

    return evaluator.run_diagnostics(
        X,
        y,
        dataset_name=dataset_name,
        fit_kwargs=fit_kwargs,
    )


def main():
    print("=" * 65)
    print("RPKClust Evaluation - NetPlier Dataset")
    print("=" * 65)

    # ------------------------------------------------------------------
    # Paths (resolved relative to this file, not the CWD)
    # ------------------------------------------------------------------

    base_dir = Path(__file__).resolve().parent
    downloads_dir = base_dir / "datasets" / "downloads"
    results_dir = base_dir / "results"

    if not downloads_dir.exists():
        raise FileNotFoundError(
            f"Dataset directory does not exist:\n"
            f"    {downloads_dir}"
        )

    # ------------------------------------------------------------------
    # Initialize evaluator and loader
    # ------------------------------------------------------------------

    evaluator = RPKClustEvaluator(
        output_dir=str(results_dir),
        fig_format="png",
        dpi=300,
    )

    pcap_loader = PcapDatasetLoader(
        target_dir=str(downloads_dir)
    )

    # ------------------------------------------------------------------
    # Find NetPlier captures
    # ------------------------------------------------------------------

    pcap_files = []

    for filename, protocol in NETPLIER_DATASETS.items():
        pcap_file = downloads_dir / filename

        if not pcap_file.exists():
            print(f"[WARNING] Missing dataset: {pcap_file}")
            continue

        pcap_files.append((pcap_file, protocol))

    if not pcap_files:
        raise FileNotFoundError(
            f"No NetPlier capture files were found in:\n"
            f"    {downloads_dir}"
        )

    print()
    print(f"Found {len(pcap_files)} NetPlier datasets:")
    print()

    for pcap_file, protocol in pcap_files:
        print(f"  {protocol:<10} -> {pcap_file.name}")

    print()

    # ------------------------------------------------------------------
    # Evaluate every NetPlier dataset.
    #
    # A failure on one dataset must not abort the whole benchmark.
    # ------------------------------------------------------------------

    failures = []

    for pcap_file, protocol in pcap_files:

        try:

            evaluate_pcap(
                loader=pcap_loader,
                evaluator=evaluator,
                pcap_file=pcap_file,
                protocol=protocol,
            )

        except Exception as exc:

            failures.append((pcap_file.name, protocol, exc))

            print()
            print(f"[FAILED] {protocol} ({pcap_file.name})")
            print(f"  {type(exc).__name__}: {exc}")
            traceback.print_exc()

    # ------------------------------------------------------------------
    # Export combined evaluation results
    # ------------------------------------------------------------------

    print()
    print("=" * 65)
    print("Exporting summary artifacts")
    print("=" * 65)

    evaluator.export_summary_artifacts()

    if failures:

        print()
        print("=" * 65)
        print("INCOMPLETE BENCHMARK")
        print("=" * 65)

        for filename, protocol, exc in failures:
            print(f"  {protocol:<10} {filename:<20} {exc}")

        print()

    print()
    print("Evaluation completed successfully.")


if __name__ == "__main__":
    main()